Repository masters2023-project-06-second-hand/second-hand-fe, pull requests merged in 2023-08, with the labels that each got.

#2 chore/#1: 개발 환경 초기 세팅
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  fe/.eslintrc.cjs
  fe/.gitignore
  fe/.prettierrc
  fe/index.html
  fe/package-lock.json
  fe/package.json
  fe/src/App.tsx
  fe/src/main.tsx
  fe/src/vite-env.d.ts
  fe/tsconfig.json
  fe/tsconfig.node.json
  fe/vite.config.ts
  fe/yarn.lock
Labels: chore, SPRINT#1

#4 design/#3: 디자인 시스템 추가
  fe/public/watermelon.png
  fe/src/assets/camera.svg
  fe/src/assets/check.svg
  fe/src/assets/chevron-down.svg
  fe/src/assets/chevron-left.svg
  fe/src/assets/chevron-right.svg
  fe/src/assets/chevron-up.svg
  fe/src/assets/circle-x-filled.svg
  fe/src/assets/dots.svg
  fe/src/assets/exclamation-circle.svg
  fe/src/assets/heart-filled.svg
  fe/src/assets/heart.svg
  fe/src/assets/home.svg
  fe/src/assets/keyboard-show.svg
  fe/src/assets/layout-grid.svg
  fe/src/assets/map-pin-filled.svg
  fe/src/assets/message-noti.svg
  fe/src/assets/message.svg
  fe/src/assets/news.svg
  fe/src/assets/paperclip.svg
  fe/src/assets/pencil.svg
  fe/src/assets/photo.svg
  fe/src/assets/plus.svg
  fe/src/assets/search.svg
  fe/src/assets/send.svg
  fe/src/assets/user-circle.svg
  fe/src/assets/x.svg
  fe/src/styles/DesignSystem.ts
  fe/src/styles/GlobalStyles.ts
  fe/src/styles/base/Colors.ts
  fe/src/styles/base/Fonts.ts
Labels: design, SPRINT#1

#12 feat/#9: TextButton 컴포넌트 구현
  fe/.storybook/main.ts
  fe/.storybook/preview.ts
  fe/package-lock.json
  fe/package.json
  fe/src/App.tsx
  fe/src/components/Button/TextButton.stories.tsx
  fe/src/components/Button/TextButton.tsx
  fe/src/components/Icon/Icon.stories.ts
  fe/src/components/Icon/Icon.tsx
Labels: chore, feat, SPRINT#1

#13 feat/#10: Header 컴포넌트 구현
  fe/.eslintrc.cjs
  fe/src/components/Header/Header.stories.tsx
  fe/src/components/Header/Header.tsx
Labels: feat, SPRINT#1

#17 feat/#7: ActionBar 컴포넌트 구현
  fe/src/components/ActionBar/ActionBar.stories.ts
  fe/src/components/ActionBar/ActionBar.tsx
  fe/src/components/Header/Header.tsx
  fe/src/components/Icon/Icon.stories.ts
  fe/src/components/Icon/Icon.tsx
  fe/src/styles/DesignSystem.ts
Labels: feat, SPRINT#1

#18 feat/#11: ProductBanner 컴포넌트 구현
  fe/src/components/ProductBanner/ProductBanner.stories.ts
  fe/src/components/ProductBanner/ProductBanner.tsx
Labels: feat, SPRINT#1

#20 refactor/#19: ActionBar, ProductBanner 컴포넌트 리팩토링
  fe/src/components/ActionBar/ActionBar.tsx
  fe/src/components/ProductBanner/ProductBanner.stories.ts
Labels: refactor, SPRINT#1

#21 feat/#15: Button 컴포넌트 구현
  fe/src/components/Button/Button.stories.tsx
  fe/src/components/Button/Button.tsx
  fe/src/styles/DesignSystem.ts
Labels: feat

#23 chore/#22: storybook 배포 세팅
  .github/workflows/chromatic.yml
  fe/package-lock.json
  fe/package.json
Labels: chore, SPRINT#1

#25 feat/#16: FabButton 컴포넌트 구현
  fe/src/components/Button/FabButton.stories.tsx
  fe/src/components/Button/FabButton.tsx
Labels: feat, SPRINT#2

#26 feat/#14: ProductItem 컴포넌트 구현
  fe/src/components/Badge/StateBadge.stories.tsx
  fe/src/components/Badge/StateBadge.tsx
  fe/src/components/Item/ProductItem.tsx
  fe/src/styles/GlobalStyles.ts
  fe/src/utils/displayCount.tsx
  fe/src/utils/displayTimeAgo.tsx
  fe/src/utils/formatPrice.tsx
  fe/src/utils/index.tsx
Labels: feat, SPRINT#2

#28 refactor/#27: Button, Header, TextButton 리팩토링
  fe/src/components/Button/Button.tsx
  fe/src/components/Button/TextButton.stories.tsx
  fe/src/components/Button/TextButton.tsx
  fe/src/components/Header/Header.stories.tsx
  fe/src/components/Header/Header.tsx
  fe/src/components/Icon/Icon.tsx
Labels: refactor, SPRINT#2

#40 add/#39: Axios 의존성 추가
  fe/package-lock.json
  fe/package.json
Labels: add, SPRINT#2

#41 refactor/#38: ActionBar 컴포넌트 구조 변경
  fe/src/components/ActionBar/ActionBar.tsx
  fe/src/components/ActionBar/EditBar.tsx
  fe/src/components/ActionBar/PostBar.tsx
Labels: refactor, SPRINT#2

#44 feat/#43: PageNav 컴포넌트 구현
  fe/src/components/PageNav/PageNav.tsx
Labels: feat, SPRINT#2

#45 feat/#34: SellerInfo 컴포넌트 구현
  fe/src/components/SellerInfo/SellerInfo.tsx
Labels: feat, SPRINT#2
