Repository masters2023-project-06-second-hand/second-hand-fe, pull requests merged in 2023-09, with the labels that each got.

#48 feat/#31: Input 컴포넌트 구현
  fe/src/components/Input/Input.tsx
  fe/src/components/Input/InputBox.tsx
  fe/src/components/Input/LabelInput.tsx
  fe/src/components/Input/PriceInput.tsx
Labels: feat, SPRINT#2

#49 feat/#30: Textarea 컴포넌트 구현
  fe/src/components/Textarea/Textarea.tsx
Labels: feat, SPRINT#2

#51 feat/#33: AddImgInput 컴포넌트 구현
  fe/src/components/AddImgInput/AddImgInput.tsx
Labels: feat, SPRINT#2

#52 feat/#36: PictureItem 컴포넌트 구현
  fe/src/components/PictureItem/PictureItem.tsx
Labels: feat, SPRINT#2

#54 feat/#53: useInput, usePrice hooks 구현
  fe/src/hooks/useInput.ts
  fe/src/hooks/usePrice.ts
Labels: feat, SPRINT#2

#56 feat/#55: constants 생성 및 추가
  fe/src/constants/constants.ts
Labels: feat, SPRINT#2

#58 feat/#57: Button 컴포넌트 추가
  fe/src/components/Button/ImgDeleteButton.tsx
  fe/src/components/Button/LikeButton.tsx
  fe/src/components/Button/SendButton.tsx
Labels: feat, SPRINT#2

#60 feat/#59: 상품 등록 페이지 구현
  fe/src/pages/AddPage.tsx
Labels: feat, SPRINT#2

#62 refactor/#61: 2주차 컴포넌트 리팩토링
  fe/src/App.tsx
  fe/src/components/ActionBar/ActionBar.tsx
  fe/src/components/ActionBar/EditBar.tsx
  fe/src/components/ActionBar/PostBar.tsx
  fe/src/components/Header/Header.tsx
  fe/src/styles/base/Colors.ts
  fe/tsconfig.json
Labels: refactor, SPRINT#2

#64 feat/#46: Modal 컴포넌트 구현
  fe/src/App.tsx
  fe/src/components/Modal/GlobalModal.tsx
  fe/src/components/Modal/Modal.tsx
  fe/src/components/Modal/index.tsx
  fe/src/components/Modal/types.tsx
  fe/src/components/Modal/useModal.tsx
Labels: feat, SPRINT#2

#63 feat/#35: Dropdown menu 컴포넌트들 구현
  .github/workflows/chromatic.yml
  fe/src/components/Dropdown/Dropdown.tsx
  fe/src/components/Dropdown/MenuDropdown.tsx
  fe/src/components/Dropdown/ReigonDropdown.tsx
  fe/src/components/Dropdown/useDropdown.tsx
Labels: feat, SPRINT#2

#66 refactor/#65: 2주차 리뷰 리팩토링
  .github/workflows/chromatic.yml
  fe/index.html
  fe/src/components/Dropdown/Dropdown.tsx
  fe/src/components/Dropdown/MenuDropdown.tsx
  fe/src/components/Dropdown/ReigonDropdown.tsx
  fe/src/components/Modal/GlobalModal.tsx
  fe/src/components/Modal/Modal.tsx
  fe/src/components/Modal/types.tsx
  fe/src/utils/displayTimeAgo.tsx
  fe/src/utils/formatPrice.tsx
Labels: refactor, SPRINT#2

#68 feat/#67: 페이지 라우터 설정
  fe/src/pages/AccountPage.tsx
  fe/src/pages/ChatPage.tsx
  fe/src/pages/HistoryPage.tsx
  fe/src/pages/HomePage.tsx
  fe/src/pages/Layout.tsx
  fe/src/pages/LikePage.tsx
  fe/src/routes/router.tsx
Labels: feat, SPRINT#3

#70 feat/#69: 필요한 page 추가 및 Layout 설정
  fe/src/App.tsx
  fe/src/components/Header/Header.tsx
  fe/src/components/NavigationBar/NavigationBar.tsx
  fe/src/pages/CategoryPage.tsx
  fe/src/pages/ErrorPage.tsx
  fe/src/pages/Layout.tsx
  fe/src/pages/Loading.tsx
  fe/src/routes/router.tsx
  fe/tsconfig.json
  fe/vite.config.ts
Labels: feat, fix, SPRINT#3

#72 feat/#69: 메인 페이지 UI 구현
  fe/src/components/Dropdown/Dropdown.tsx
  fe/src/components/Header/Header.tsx
  fe/src/components/Item/ProductItem.tsx
  fe/src/components/Modal/GlobalModal.tsx
  fe/src/pages/HomePage.tsx
  fe/src/pages/Layout.tsx
Labels: feat, SPRINT#3

#73 feat/#71: Category 페이지 UI 구현
  fe/src/pages/CategoryPage.tsx
  fe/src/routes/router.tsx
Labels: feat, SPRINT#3

#77 feat/#76: axios 설정, 환경 변수 설정
  fe/src/api/constants.tsx
  fe/src/api/index.tsx
  fe/tsconfig.json
  fe/vite.config.ts
Labels: feat, SPRINT#3

#79 feat/#78: category 목록 관련 요청 추가
  fe/package.json
  fe/public/mockServiceWorker.js
  fe/src/api/category/types.tsx
  fe/src/api/category/useCategories.tsx
  fe/src/api/constants.tsx
  fe/src/main.tsx
  fe/src/mocks/data/categories.tsx
  fe/src/mocks/data/productList.tsx
  fe/src/mocks/handler.tsx
  fe/src/mocks/workers.tsx
  fe/src/pages/CategoryPage.tsx
  fe/src/react-query/queryKey.tsx
  fe/tsconfig.json
  fe/vite.config.ts
Labels: chore, feat, SPRINT#3

#80 feat/#74: 내 계정 페이지 UI 구현
  fe/public/google.png
  fe/public/naver.png
  fe/src/pages/AccountPage.tsx
Labels: feat, SPRINT#3

#82 feat/#81: 회원가입 페이지 UI 구현
  fe/src/pages/JoinPage.tsx
  fe/src/routes/router.tsx
Labels: feat, SPRINT#3

#83 feat/#37: ProfileImgInput 컴포넌트 구현
  fe/src/components/ProfileImgInput/ProfileImgInput.tsx
Labels: feat, SPRINT#3

#84 feat/#42: Tag 컴포넌트 구현
  fe/src/components/Tag/Tag.tsx
Labels: feat, SPRINT#3

#87 fix/#86: 글 목록이 위로 올라오는 현상 수정
  fe/src/components/Dropdown/Dropdown.tsx
  fe/src/components/Header/Header.tsx
  fe/src/components/Modal/GlobalModal.tsx
  fe/src/components/NavigationBar/NavigationBar.tsx
  fe/src/pages/HomePage.tsx
Labels: fix, SPRINT#3

#88 feat/#85: Callback 페이지 구현
  fe/src/pages/CallbackPage.tsx
  fe/src/routes/router.tsx
Labels: feat, SPRINT#3

#90 feat/#89: 판매내역, 관심상품 페이지 UI 작업
  fe/src/components/Button/FabButton.tsx
  fe/src/components/Dropdown/Dropdown.tsx
  fe/src/components/Item/ProductItem.tsx
  fe/src/components/Item/getDropdownItem.tsx
  fe/src/components/NavigationBar/NavigationBar.tsx
  fe/src/pages/HistoryPage.tsx
  fe/src/pages/Layout.tsx
  fe/src/pages/LikePage.tsx
  fe/src/stories/Button.stories.ts
  fe/src/stories/Button.tsx
  fe/src/stories/Configure.mdx
  fe/src/stories/Header.stories.ts
  fe/src/stories/Header.tsx
  fe/src/stories/Page.stories.ts
  fe/src/stories/Page.tsx
  fe/src/stories/assets/accessibility.png
  fe/src/stories/assets/accessibility.svg
  fe/src/stories/assets/addon-library.png
  fe/src/stories/assets/assets.png
  fe/src/stories/assets/context.png
  fe/src/stories/assets/discord.svg
  fe/src/stories/assets/docs.png
  fe/src/stories/assets/figma-plugin.png
  fe/src/stories/assets/github.svg
  fe/src/stories/assets/share.png
  fe/src/stories/assets/styling.png
  fe/src/stories/assets/testing.png
  fe/src/stories/assets/theming.png
  fe/src/stories/assets/tutorials.svg
  fe/src/stories/assets/youtube.svg
  fe/src/stories/button.css
  fe/src/stories/header.css
  fe/src/stories/page.css
Labels: feat, SPRINT#3

#92 test/#91: 유틸 함수 테스트 코드 추가
  fe/jest.config.ts
  fe/package-lock.json
  fe/package.json
  fe/src/test/displayTimeAgo.test.ts
  fe/src/test/formatPrice.test.ts
  fe/tsconfig.json
Labels: chore, SPRINT#3

#95 feat/#93: States 컴포넌트 구현
  fe/src/components/States/States.tsx
Labels: feat, SPRINT#3

#96 refactor/#94: 3주차 컴포넌트 리팩토링
  fe/src/components/ActionBar/ActionBar.stories.ts
  fe/src/components/ActionBar/ActionBar.tsx
  fe/src/components/Header/Header.tsx
  fe/src/components/Input/PriceInput.tsx
  fe/src/components/SellerInfo/SellerInfo.tsx
  fe/src/components/Tag/Tag.tsx
  fe/src/components/Textarea/Textarea.tsx
  fe/src/constants/constants.ts
  fe/src/pages/AccountPage.tsx
  fe/src/pages/AddPage.tsx
  fe/src/pages/CallbackPage.tsx
  fe/src/pages/CategoryPage.tsx
  fe/src/pages/HistoryPage.tsx
  fe/src/pages/HomePage.tsx
  fe/src/pages/Layout.tsx
  fe/src/pages/LikePage.tsx
Labels: refactor, SPRINT#3

#97 feat/#75: 상품 상세 페이지 UI 구현
  fe/src/pages/DetailPage.tsx
  fe/src/routes/router.tsx
  fe/src/utils/generateRecommendCategory.tsx
Labels: feat, SPRINT#3

#99 fix/#98: 라우터 오류 수정
  fe/src/routes/router.tsx
Labels: fix, SPRINT#3

#101 fix/#100: 상품 추가 페이지 버그 수정
  fe/src/pages/AddPage.tsx
Labels: feat, SPRINT#3

#103 refactor/#102: 3주차 리뷰 리팩토링
  fe/src/api/category/useCategories.tsx
  fe/src/components/ActionBar/ActionBar.tsx
  fe/src/components/ActionBar/PostBar.tsx
  fe/src/components/AddImgInput/AddImgInput.tsx
  fe/src/components/Badge/StateBadge.tsx
  fe/src/components/Button/Button.tsx
  fe/src/components/Button/FabButton.tsx
  fe/src/components/Button/ImgDeleteButton.tsx
  fe/src/components/Button/LikeButton.tsx
  fe/src/components/Button/SendButton.tsx
  fe/src/components/Button/TextButton.tsx
  fe/src/components/Dropdown/Dropdown.tsx
  fe/src/components/Dropdown/ReigonDropdown.tsx
  fe/src/components/Header/Header.tsx
  fe/src/components/Input/Input.tsx
  fe/src/components/Input/InputBox.tsx
  fe/src/components/Input/LabelInput.tsx
  fe/src/components/Input/PriceInput.tsx
  fe/src/components/Item/ProductItem.tsx
  fe/src/components/Modal/GlobalModal.tsx
  fe/src/components/Modal/Modal.tsx
  fe/src/components/NavigationBar/NavigationBar.tsx
  fe/src/components/PictureItem/PictureItem.tsx
  fe/src/components/ProductBanner/ProductBanner.tsx
  fe/src/components/ProfileImgInput/ProfileImgInput.tsx
  fe/src/components/States/States.tsx
  fe/src/components/Tag/Tag.tsx
  fe/src/components/Textarea/Textarea.tsx
  fe/src/constants/path.ts
  fe/src/constants/queryKey.tsx
  fe/src/hooks/usePageNavigator.ts
  fe/src/pages/AccountPage.tsx
  fe/src/pages/AddPage.tsx
  fe/src/pages/CategoryPage.tsx
  fe/src/pages/DetailPage.tsx
  fe/src/pages/ErrorPage.tsx
  fe/src/pages/HistoryPage.tsx
  fe/src/pages/HomePage.tsx
  fe/src/pages/JoinPage.tsx
  fe/src/pages/Layout.tsx
  fe/src/pages/Loading.tsx
  fe/src/routes/router.tsx
Labels: refactor, SPRINT#4

#109 feat/#104: 메인 페이지 동네 설정 기능
  fe/src/App.tsx
  fe/src/api/auth/login.tsx
  fe/src/api/auth/userInfo.tsx
  fe/src/api/category/useCategories.tsx
  fe/src/api/constants.tsx
  fe/src/api/index.tsx
  fe/src/api/queryKey.tsx
  fe/src/api/region/region.tsx
  fe/src/atoms/loginAtom.tsx
  fe/src/atoms/userAtom.tsx
  fe/src/components/Dropdown/ReigonDropdown.tsx
  fe/src/components/Modal/Modal.tsx
  fe/src/components/Modal/RegionSettingModal.tsx
  fe/src/components/Modal/index.tsx
  fe/src/constants/constants.ts
  fe/src/constants/endpoints.ts
  fe/src/envConfig.ts
  fe/src/pages/AccountPage.tsx
  fe/src/pages/CallbackPage.tsx
  fe/src/pages/HomePage.tsx
Labels: feat, refactor, SPRINT#4

#110 feat/#104: SearchRegionModal에 Input 적용
  fe/src/components/Modal/Modal.tsx
  fe/src/components/Modal/SearchRegionModal.tsx
  fe/src/components/Modal/index.tsx
  fe/src/hooks/useDebounce.ts
Labels: feat, SPRINT#4

#111 feat/#106: 상품 상세 페이지 기능 구현
  fe/src/api/product/types.tsx
  fe/src/api/product/useProductDetail.tsx
  fe/src/api/queryKey.tsx
  fe/src/constants/constants.ts
  fe/src/constants/endpoints.ts
  fe/src/constants/path.ts
  fe/src/pages/DetailPage.tsx
  fe/src/routes/router.tsx
Labels: feat, SPRINT#4

#113 refactor/#112: 상품 상세 페이지 리팩토링
  fe/src/api/product/product.tsx
  fe/src/api/product/useProductDetail.tsx
  fe/src/pages/DetailPage.tsx
Labels: refactor

#117 refactor/#114: 4주차 리팩토링
  fe/src/api/auth/login.tsx
  fe/src/api/region/region.tsx
  fe/src/components/Dropdown/ReigonDropdown.tsx
  fe/src/pages/CallbackPage.tsx
Labels: refactor, SPRINT#5

#116 feat/#115: 상품 상세 페이지 수정 기능 추가
  fe/src/api/product/product.tsx
  fe/src/components/Dropdown/ReigonDropdown.tsx
  fe/src/components/Modal/RegionSettingModal.tsx
  fe/src/pages/HomePage.tsx
  fe/src/pages/Product/AddPage.tsx
  fe/src/pages/Product/DetailPage.tsx
  fe/src/pages/Product/ProductPage.tsx
  fe/src/routes/router.tsx
  fe/src/utils/extractRegionName.tsx
Labels: feat, SPRINT#5

#120 Feat/#118 feat toast 구현하기
  fe/src/App.tsx
  fe/src/api/auth/login.tsx
  fe/src/atoms/toastAtom.tsx
  fe/src/components/Toast/Toast.tsx
  fe/src/components/Toast/useToast.tsx
Labels: feat, SPRINT#5

#122 feat/#121: 내 동네 삭제 기능 추가
  fe/src/api/region/region.tsx
  fe/src/components/Modal/RegionSettingModal.tsx
Labels: feat, SPRINT#5

#124 feat/#123: 메인 상품 목록 렌더링 구현
  fe/src/api/product/productList.tsx
  fe/src/api/queryKey.tsx
  fe/src/atoms/categoryAtom.tsx
  fe/src/components/Item/ProductItem.tsx
  fe/src/constants/endpoints.ts
  fe/src/hooks/useInfiniteScroll.ts
  fe/src/pages/CategoryPage.tsx
  fe/src/pages/HomePage.tsx
Labels: feat, SPRINT#5

#126 feat/#105: 상품 추가 페이지 기능 구현
  fe/src/api/images/images.tsx
  fe/src/api/images/type.tsx
  fe/src/api/index.tsx
  fe/src/api/product/product.tsx
  fe/src/api/product/types.tsx
  fe/src/api/region/region.tsx
  fe/src/atoms/userAtom.tsx
  fe/src/components/ActionBar/EditBar.tsx
  fe/src/components/ActionBar/PostBar.tsx
  fe/src/components/Dropdown/Dropdown.tsx
  fe/src/components/Dropdown/MenuDropdown.tsx
  fe/src/components/Modal/CategoryModal.tsx
  fe/src/components/Modal/Modal.tsx
  fe/src/components/Modal/index.tsx
  fe/src/components/Modal/types.tsx
  fe/src/constants/endpoints.ts
  fe/src/pages/Product/AddPage.tsx
  fe/src/pages/Product/DetailPage.tsx
Labels: feat, SPRINT#5

#127 feat/#125: 상품 리스트 상태 변경 기능
  fe/src/components/BottomMenu/BottomMenu.tsx
  fe/src/components/BottomMenu/getProductStatus.tsx
  fe/src/components/Item/ProductItem.tsx
Labels: feat, SPRINT#5

#129 refactor/#128: 5주차 리팩토링
  fe/src/api/images/images.tsx
  fe/src/api/liked/liked.tsx
  fe/src/api/product/product.tsx
  fe/src/api/product/types.tsx
  fe/src/api/queryKey.tsx
  fe/src/components/ActionBar/PostBar.tsx
  fe/src/components/Dropdown/Dropdown.tsx
  fe/src/components/Item/ProductItem.tsx
  fe/src/constants/endpoints.ts
  fe/src/constants/path.ts
  fe/src/hooks/usePageNavigator.ts
  fe/src/pages/Product/AddPage.tsx
  fe/src/pages/Product/DetailPage.tsx
  fe/src/pages/Product/ProductPage.tsx
Labels: refactor, SPRINT#5

#131 feat/#130: 동네 추가 기능 구현
  fe/src/api/images/images.tsx
  fe/src/api/liked/liked.tsx
  fe/src/api/queryKey.tsx
  fe/src/api/region/regionList.tsx
  fe/src/components/Dropdown/ReigonDropdown.tsx
  fe/src/components/Modal/RegionSettingModal.tsx
  fe/src/components/Modal/SearchRegionModal.tsx
  fe/src/components/Modal/types.tsx
  fe/src/constants/endpoints.ts
Labels: feat, SPRINT#5
